"""
Portfolio Project #2 - ReLoop Crate Systems
Visualization Module

Purpose:
    Create Matplotlib visualizations from the KPI outputs
    generated by EDA.py.

Architecture:
    Data_Cleaning.py -> EDA.py -> Visualization.py

EDA.py owns data preparation and business calculations.
Visualization.py owns charts and visual formatting.
"""

import matplotlib.pyplot as plt

# Import the completed KPI results from EDA.py.
# Importing the module gives this file access to the DataFrames
# created during the analysis without duplicating the KPI logic.
import EDA as eda


# ==========================================================
# Load KPI Data for Visualization
# ==========================================================

# BA-01: Top Customers by Net Revenue
top_customers = eda.top_customers.copy()

# BA-03: Revenue by Customer Region
top_region_revenue = eda.top_region_revenue.copy()

# BA-04: Monthly Revenue Trend
monthly_revenue = eda.monthly_revenue.copy()

# BA-09: Average Rental Days by Crate Model
average_rental_days = eda.average_rental_days.copy()

# BA-11: Revenue by Contract Tier
contract_details = eda.contract_details.copy()

# BA-12: Supplier Performance
supplier_details = eda.supplier_details.copy()

# BA-13: Deployment Trend Analysis
deployment_summary = eda.deployment_summary.copy()


# ==========================================================
# Chart 1: Monthly Deployment Trend
# ==========================================================
def plot_deployment_trend():
    """Plot monthly deployment volume over time."""

    chart_data = deployment_summary.copy()
    chart_data["Period"] = (
        chart_data["Year"].astype(str)
        + "-"
        + chart_data["Month_No"].astype(str).str.zfill(2)
    )

    plt.figure(figsize=(12, 5))
    plt.plot(
        chart_data["Period"],
        chart_data["Total_Deployments"]
    )

    plt.title("Monthly Deployment Trend")
    plt.xlabel("Month")
    plt.ylabel("Total Deployments")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


# ==========================================================
# Chart 2: Revenue by Contract Tier
# ==========================================================
def plot_revenue_by_contract_tier():
    """Compare net revenue generated by contract tier."""

    chart_data = contract_details.sort_values(
        "Net_Revenue",
        ascending=False
    )

    plt.figure(figsize=(9, 5))
    plt.bar(
        chart_data["contract_tier"],
        chart_data["Net_Revenue"]
    )

    plt.title("Net Revenue by Contract Tier")
    plt.xlabel("Contract Tier")
    plt.ylabel("Net Revenue")
    plt.xticks(rotation=30)
    plt.tight_layout()
    plt.show()


# ==========================================================
# Chart 3: Top 10 Customers by Net Revenue
# ==========================================================
def plot_top_customers():
    """Plot the top 10 customers by net revenue."""

    chart_data = (
        top_customers
        .sort_values("Net_Revenue", ascending=True)
        .tail(10)
    )

    plt.figure(figsize=(10, 6))
    plt.barh(
        chart_data["legal_name"],
        chart_data["Net_Revenue"]
    )

    plt.title("Top 10 Customers by Net Revenue")
    plt.xlabel("Net Revenue")
    plt.ylabel("Customer")
    plt.tight_layout()
    plt.show()


# ==========================================================
# Chart 4: Supplier Average Freight Cost
# ==========================================================
def plot_supplier_freight_cost():
    """Plot average freight cost for suppliers."""

    chart_data = (
        supplier_details
        .sort_values("Average_Freight_Cost", ascending=False)
        .head(10)
        .sort_values("Average_Freight_Cost", ascending=True)
    )

    plt.figure(figsize=(10, 6))
    plt.barh(
        chart_data["supplier_name"],
        chart_data["Average_Freight_Cost"]
    )

    plt.title("Top 10 Suppliers by Average Freight Cost")
    plt.xlabel("Average Freight Cost")
    plt.ylabel("Supplier")
    plt.tight_layout()
    plt.show()


# ==========================================================
# Run Charts
# ==========================================================
# Keeping chart calls inside this block means importing this
# module will load the data and define the charts, but will not
# automatically open four chart windows.
# ==========================================================

if __name__ == "__main__":
    plot_deployment_trend()
    plot_revenue_by_contract_tier()
    plot_top_customers()
    plot_supplier_freight_cost()